const { chromium } = require('playwright');
const OUT = '/tmp/claude-0/-home-user-learning/d9454b66-4e73-5742-9599-3801914aa20a/scratchpad/';
(async () => {
  const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
  const scheme = process.argv[2] || 'dark';
  const page = await (await browser.newContext({ viewport: { width: 375, height: 800 }, colorScheme: scheme, reducedMotion: 'reduce' })).newPage();
  await page.goto('file:///home/user/learning/lessons/1501-drive-scope-and-apis.html');
  const shot = async (sel, name) => { await page.locator(sel).scrollIntoViewIfNeeded(); await page.evaluate(s => { const e = document.querySelector(s); window.scrollTo(0, e.getBoundingClientRect().top + scrollY - 90); }, sel); await page.waitForTimeout(250); await page.screenshot({ path: OUT + `s-${scheme}-${name}.png` }); };
  await page.click('#bins .binbtn[data-b="F"]'); await page.waitForTimeout(1700);
  await shot('#s1 .tray', 'tray');
  await shot('#rack', 'rack');
  await page.click('#doors .door[data-d="rev"]');
  await page.click('#modeSeg button[data-m="resumable"]');
  await page.click('#upGo');
  await page.waitForSelector('#upResume', { state: 'visible' });
  await shot('#apicode', 'api');
  await shot('#upsvg', 'upload');
  await page.click('#fillBtn'); await page.waitForTimeout(600);
  await shot('#arch', 'archA');
  await page.locator('#abox button', { hasText: 'Shard files' }).click();
  await page.locator('#abox button', { hasText: 'Round 2' }).click();
  await page.locator('#abox button', { hasText: 'Every file' }).click();
  await shot('#arch', 'archB');
  await page.locator('#abox button', { hasText: 'Move the files' }).click();
  await page.locator('#abox button', { hasText: 'Take Region' }).click();
  await page.waitForTimeout(800);
  await shot('#arch', 'archC');
  await page.locator('#abox button', { hasText: 'Round 3' }).click();
  await page.locator('#arch g[role="button"][aria-label^="Web server"]').click();
  await page.locator('#spof button', { hasText: 'A load balancer' }).click();
  await page.locator('#arch g[role="button"][aria-label^="MySQL"]').click();
  await page.locator('#spof button', { hasText: 'Move it off' }).click();
  await page.waitForTimeout(600);
  await shot('#arch', 'archD');
  await shot('#boss', 'boss');
  await browser.close();
})();
